server:
  port: 8080

spring:
  application:
    name: finalyzer
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://192.168.65.12:3306/finalyzer?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: finalyzer
    password: finalyzerpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO
    com.bocopile: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always

  metrics:
    tags:
      application: finalyzer
    export:
      otlp:
        enabled: true
        url: http://otel-opentelemetry-collector.tracing.svc.cluster.local:4317   # K8s ?? ?? (?? ??)
        step: 30s
      prometheus:
        enabled: true

  tracing:
    enabled: true

etf:
  client:
    vantage:
      url: "https://www.alphavantage.co/query"
      function: "TIME_SERIES_DAILY"
      api-key: "BPFW7GPDD8ZEEG5V"
    naver:
      url-template: "https://finance.naver.com/item/sise_day.nhn?code=%s&page=1"
      user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
    etfdb:
      base-url: "https://etfdb.com/etf/%s/"
      # 예: https://etfdb.com/etf/SPY/
      user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
    kodex:
      base-url: "https://m.samsungfund.com/etf/main.do?symbol=%s"
      user-agent: "Mozilla/5.0 (compatible; FinalyzerBot/1.0)"
